//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTracker
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public System.DateTime ApprovedAt { get; set; }
        public Nullable<System.DateTime> AssignedAt { get; set; }
        public Nullable<System.DateTime> DeliveredAt { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
