//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.OrderTrackers = new HashSet<OrderTracker>();
            this.Payments = new HashSet<Payment>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public double ProductTotal { get; set; }
        public double ShippingCharge { get; set; }
        public double Total { get; set; }
        public int OrderStatusID { get; set; }
        public string CancelledBy { get; set; }
        public Nullable<System.DateTime> CancelledAt { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> DeliveryManId { get; set; }
        public Nullable<System.DateTime> DeliveredAt { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Deliveryman Deliveryman { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderTracker> OrderTrackers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
