//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int PaymentMethodId { get; set; }
        public double Amount { get; set; }
        public int PaymentStatusId { get; set; }
        public Nullable<System.DateTime> ProcessedAt { get; set; }
        public Nullable<int> TransactionTypeId { get; set; }
    
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual PaymentStatus PaymentStatus { get; set; }
        public virtual TransactionType TransactionType { get; set; }
        public virtual Order Order { get; set; }
    }
}
